@startuml
'-----------skin param setting------------------------------------------------------
skinparam sequenceArrowThickness 2
skinparam roundCorner 2
skinparam agentBorderColor Green

'skinparam monochrome reverse
'skinparam sequenceMessageAlign left
skinparam participantBorderColor Green
skinparam participantFontSize 9啥
'-----------title---------------------------------------------------------

hide footbox
title Receive Block Sequence Diagram
participant "producer_plugin.cpp\n producer_plugin " as pp
participant "producer_plugin.cpp\n producer_plugi_impl" as ppi
participant "controller.cpp\n controller" as cc
participant "controller.cpp\n controller_impl" as cci
participant fork_db

[o->ppi: on_incoming_block
activate ppi
    ppi->cc: push_block
deactivate ppi
    activate cc
        cc->cci: push_block
    deactivate cc
        activate cci
            create fork_db
            cci-->fork_db:add
            cci->cci:maybe_switch_forks
                activate cci
                cci->cci: apply_block
                    activate cci
group same as produce block
                    cci->cci: start_block
                        activate cci
                        deactivate cci
end
                    cci->cci: push_transaction \npush_scheduled_transaction
                        activate cci
                        deactivate cci
                    cci->cci: finalize_block
                        activate cci
                        deactivate cci
                    cci->cci: commit_block
                    note left
                    not add
                    fork_db
                    end note
                       activate cci
                        deactivate cci

                    deactivate cci
                cci->fork_db: mark_in_current_chain, set_validity
                deactivate cci
        deactivate cci

@enduml